# Generated by Django 3.1.7 on 2021-03-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Когда создан?')),
                ('num_pages', models.IntegerField(blank=True, verbose_name='Сколько страниц?')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Когда создан?')),
                ('type', models.SmallIntegerField(choices=[(1, 'bullet'), (2, 'food'), (3, 'travel'), (4, 'sport')], default=1, verbose_name='Вид журнала')),
                ('publisher', models.CharField(max_length=100, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
    ]
